# Generated by Django 4.2.1 on 2023-06-07 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    # dependencies = [
    #     ('store', '0006_Create_review_model'),
    # ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
