# Generated by Django 4.2.1 on 2023-07-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('cart', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
